services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
      # Optional: remove or validate this if not needed or broken
      # - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - '${DB_PORT}:3306'
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -u$$DB_USER -p$$DB_ROOT_PASSWORD --silent || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
