version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: amby-db
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
  app:
    build: .
    container_name: amby-craft-be-service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: amby-db
    depends_on:
      - db
