version: '3'
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3808:3808'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: theophilus.paintsil@coderaccoon.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - db
