services:
  mariadb:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
